services:
  postgres:
    image: 'postgres:15.3'
    environment:
      - 'POSTGRES_DB=rps-user-page'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
#    volumes:
#      - postgresql_data:/var/lib/postgresql/rps-user-page